[tool.poetry]
name = "stratified-models"
version = "0.1.0"
description = ""
authors = ["Tom Shlomo <tomshlomo@gmail.com>"]
readme = "README.md"
packages = [{include = "stratified_models"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
