[project]
name = "stratified-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tom shlomo", email = "tom.shlomo@ridewithvia.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.7.5",
    "networkx>=3.6.1",
    "numpy>=2.4.1",
    "optuna>=4.7.0",
    "pandas>=3.0.0",
    "scipy>=1.17.0",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.13",
]
